# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            dhokes
tagline:          learning web development
description:      learning by doing
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'dhokes'
  url:            https://twitter.com/b_dhokia

paginate:         5

# Custom vars
version:          2.1.0

github:			  https://github.com/dhokes
repo:           https://github.com/poole/hyde
twitter:		  https://twitter.com/b_dhokia
goodreads:		  https://www.goodreads.com/dhokes 
instagram:		  https://instagram.com/dhokes